apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress  # Custom namespace added to avoid default namespace
data:
  WORDPRESS_DB_HOST: "mysql"
  WORDPRESS_DB_NAME: "{{ .Values.mysql.database }}"
  WORDPRESS_DB_USER: "{{ .Values.mysql.user }}"
  WORDPRESS_DB_PASSWORD: "{{ .Values.mysql.password }}"
