apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app.kubernetes.io/instance: wordpress
    type: ebs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
