apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  root_password: cm9vdHBhc3N3b3Jk   # base64 of rootpassword
  user: d3BfdXNlcg==               # base64 of wp_user
  password: d3BfcGFzc3dvcmQ=       # base64 of wp_password
