apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app.kubernetes.io/instance: wordpress
    type: ebs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp3
  awsElasticBlockStore:
    volumeID: vol-0a73671035a1dcb33  # <-- Make sure this is correct
    fsType: ext4
