apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: ebs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp3
  awsElasticBlockStore:
    volumeID: vol-0a73671035a1dcb33   # <-- Replace with your actual EBS volume ID
    fsType: ext4
