apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-apache-config
  namespace: wordpress
data:
  000-default.conf: |
    <VirtualHost *:80>
      DocumentRoot /var/www/html
      <Directory /var/www/html>
        AllowOverride All
        Require all granted
      </Directory>
    </VirtualHost>

  ports.conf: |
    Listen 80
