apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: "Always"
      initContainers:
        - name: volume-prep
          image: busybox:1.35
          command: ["sh", "-c", "sleep 5 && mkdir -p /var/www/html && chown -R 33:33 /var/www/html && chmod -R 775 /var/www/html"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
      containers:
        - name: wordpress
          image: wordpress:6.7-apache
          securityContext:
            runAsUser: 33  # WordPress runs as user 33 (www-data)
            runAsGroup: 33  # Group 33 (www-data)
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql.wordpress.svc.cluster.local:3306"
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: WORDPRESS_DB_NAME
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                define('FS_METHOD', 'direct');
                define('WP_HOME', 'http://docs.cloudmasa.com');
                define('WP_SITEURL', 'http://docs.cloudmasa.com');
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
            - name: apache-config
              mountPath: /etc/apache2/sites-available/000-default.conf
              subPath: 000-default.conf
            - name: apache-config
              mountPath: /etc/apache2/ports.conf
              subPath: ports.conf
            - name: apache-config
              mountPath: /etc/apache2/conf-available/servername.conf
              subPath: servername.conf  # Add this to resolve ServerName issue
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 150
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc
        - name: apache-config
          configMap:
            name: wordpress-apache-config
