apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80         # Port ALB will use
      targetPort: 8089   # ✅ Must match container port in the pod
  type: ClusterIP
