apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-apache-config
  namespace: wordpress
data:
  000-default.conf: |
    <VirtualHost *:80>
        ServerName localhost  # Add ServerName here
        DocumentRoot /var/www/html
        <Directory /var/www/html>
            AllowOverride All
            Require all granted
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>

  ports.conf: |
    Listen 80

  servername.conf: |
    ServerName localhost  # Add ServerName here to resolve the Apache warning
