apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress  # Ensure this matches your namespace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"                # Use NLB
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  # Public access
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"      # Needed for IP target type if using IP mode
spec:
  type: LoadBalancer
  selector:
    app: wordpress  # Ensure your Deployment has label app=wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8089  # This MUST match the containerPort defined in your Deployment
