apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 33  # www-data user (UID 33)
        fsGroup: 33    # www-data group (GID 33)
        fsGroupChangePolicy: "OnRootMismatch"
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      initContainers:
        - name: init-permissions
          image: busybox:1.35
          command: ["sh", "-c", "chown -R 33:33 /var/www/html && chmod -R 755 /var/www/html"]
          securityContext:
            runAsUser: 33  # Changed from 0 to maintain non-root policy
            runAsGroup: 33
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
      containers:
        - name: wordpress
          image: wordpress:6.7-apache
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql.wordpress.svc.cluster.local:3306"
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: WORDPRESS_DB_NAME
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                define('FS_METHOD', 'direct');
                define('WP_HOME', 'http://${WORDPRESS_SERVICE_HOST}');
                define('WP_SITEURL', 'http://${WORDPRESS_SERVICE_HOST}');
            # Apache-specific environment variables
            - name: APACHE_RUN_USER
              value: www-data
            - name: APACHE_RUN_GROUP
              value: www-data
            - name: APACHE_LOG_DIR
              value: /var/log/apache2
            - name: SERVERNAME
              value: localhost
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
            - name: apache-logs
              mountPath: /var/log/apache2
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60  # Increased for initialization
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30  # Increased for initialization
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 33
            runAsGroup: 33
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc
        - name: apache-logs
          emptyDir: {}
