apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000  # WordPress typically runs as www-data (UID 33 in Debian)
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      initContainers:
        - name: init-permissions
          image: busybox:1.35
          command: ["sh", "-c", "chown -R 1000:1000 /var/www/html && chmod -R 755 /var/www/html"]
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
      containers:
        - name: wordpress
          image: wordpress:6.7
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql.wordpress.svc.cluster.local:3306"
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: WORDPRESS_DB_NAME
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                define('FS_METHOD', 'direct');
            # Fix for Apache errors
            - name: APACHE_CONFDIR
              value: "/etc/apache2"
            - name: APACHE_RUN_USER
              value: "www-data"
            - name: APACHE_RUN_GROUP
              value: "www-data"
            - name: APACHE_RUN_DIR
              value: "/var/run/apache2"
            - name: APACHE_PID_FILE
              value: "/var/run/apache2/apache2.pid"
            - name: APACHE_LOCK_DIR
              value: "/var/lock/apache2"
            - name: APACHE_LOG_DIR
              value: "/var/log/apache2"
            - name: APACHE_SERVERNAME
              value: "localhost"
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
            # Additional volume mounts for Apache
            - name: apache-run
              mountPath: /var/run/apache2
            - name: apache-lock
              mountPath: /var/lock/apache2
            - name: apache-log
              mountPath: /var/log/apache2
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            # WordPress/Apache typically runs as www-data (UID 33)
            runAsUser: 33
            runAsGroup: 33
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc
        # Additional volumes for Apache
        - name: apache-run
          emptyDir: {}
        - name: apache-lock
          emptyDir: {}
        - name: apache-log
          emptyDir: {}
