apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80         # Port ALB will forward to
      targetPort: 8089 # The containerPort in your WordPress pod
  type: ClusterIP
